# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YogaKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YogaKitDemo
  pod 'YogaKit'
  pod 'Masonry'
end
