# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottieDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottieDemo
  pod 'lottie-ios','~> 2.5.0'


end
