//
//  ProgressBarDraw.m
//  ProgressFun
//
//  Created by Tassel on 2019/6/24.
//  Copyright © 2019 Tassel.Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "ProgressBarDraw.h"


@implementation ProgressBarDraw

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawProgressBarWithFrame: (CGRect)frame progress: (CGFloat)progress
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 0 blue: 0 alpha: 1];
    
    //// Progress Border Drawing
    UIBezierPath* progressBorderPath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(frame) + 1, CGRectGetMinY(frame) + 1, floor((frame.size.width - 1) * 1.00000 + 0.5), 14) cornerRadius: 7];
    [color setStroke];
    progressBorderPath.lineWidth = 1;
    [progressBorderPath stroke];
    
    
    //// Progress Active Drawing
    UIBezierPath* progressActivePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(1, 1, progress, 14) cornerRadius: 7];
    [color setFill];
    [progressActivePath fill];

}

@end
