//
//  ProgressBarDraw.h
//  ProgressFun
//
//  Created by Tassel on 2019/6/24.
//  Copyright © 2019 Tassel.Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>


@interface ProgressBarDraw : NSObject

// Drawing Methods
+ (void)drawProgressBarWithFrame: (CGRect)frame progress: (CGFloat)progress;

@end
